#
# Autogenerated by Thrift Compiler (0.9.1)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException
from ttypes import *
from thrift.Thrift import TProcessor
from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None


class Iface:
  def parse(self, billercode, productcode, billnumber, bit61):
    """
    Parameters:
     - billercode
     - productcode
     - billnumber
     - bit61
    """
    pass

  def parse_prepaid(self, billercode, productcode, billnumber, bit61, bit48):
    """
    Parameters:
     - billercode
     - productcode
     - billnumber
     - bit61
     - bit48
    """
    pass


class Client(Iface):
  def __init__(self, iprot, oprot=None):
    self._iprot = self._oprot = iprot
    if oprot is not None:
      self._oprot = oprot
    self._seqid = 0

  def parse(self, billercode, productcode, billnumber, bit61):
    """
    Parameters:
     - billercode
     - productcode
     - billnumber
     - bit61
    """
    self.send_parse(billercode, productcode, billnumber, bit61)
    return self.recv_parse()

  def send_parse(self, billercode, productcode, billnumber, bit61):
    self._oprot.writeMessageBegin('parse', TMessageType.CALL, self._seqid)
    args = parse_args()
    args.billercode = billercode
    args.productcode = productcode
    args.billnumber = billnumber
    args.bit61 = bit61
    args.write(self._oprot)
    self._oprot.writeMessageEnd()
    self._oprot.trans.flush()

  def recv_parse(self):
    (fname, mtype, rseqid) = self._iprot.readMessageBegin()
    if mtype == TMessageType.EXCEPTION:
      x = TApplicationException()
      x.read(self._iprot)
      self._iprot.readMessageEnd()
      raise x
    result = parse_result()
    result.read(self._iprot)
    self._iprot.readMessageEnd()
    if result.success is not None:
      return result.success
    raise TApplicationException(TApplicationException.MISSING_RESULT, "parse failed: unknown result");

  def parse_prepaid(self, billercode, productcode, billnumber, bit61, bit48):
    """
    Parameters:
     - billercode
     - productcode
     - billnumber
     - bit61
     - bit48
    """
    self.send_parse_prepaid(billercode, productcode, billnumber, bit61, bit48)
    return self.recv_parse_prepaid()

  def send_parse_prepaid(self, billercode, productcode, billnumber, bit61, bit48):
    self._oprot.writeMessageBegin('parse_prepaid', TMessageType.CALL, self._seqid)
    args = parse_prepaid_args()
    args.billercode = billercode
    args.productcode = productcode
    args.billnumber = billnumber
    args.bit61 = bit61
    args.bit48 = bit48
    args.write(self._oprot)
    self._oprot.writeMessageEnd()
    self._oprot.trans.flush()

  def recv_parse_prepaid(self):
    (fname, mtype, rseqid) = self._iprot.readMessageBegin()
    if mtype == TMessageType.EXCEPTION:
      x = TApplicationException()
      x.read(self._iprot)
      self._iprot.readMessageEnd()
      raise x
    result = parse_prepaid_result()
    result.read(self._iprot)
    self._iprot.readMessageEnd()
    if result.success is not None:
      return result.success
    raise TApplicationException(TApplicationException.MISSING_RESULT, "parse_prepaid failed: unknown result");


class Processor(Iface, TProcessor):
  def __init__(self, handler):
    self._handler = handler
    self._processMap = {}
    self._processMap["parse"] = Processor.process_parse
    self._processMap["parse_prepaid"] = Processor.process_parse_prepaid

  def process(self, iprot, oprot):
    (name, type, seqid) = iprot.readMessageBegin()
    if name not in self._processMap:
      iprot.skip(TType.STRUCT)
      iprot.readMessageEnd()
      x = TApplicationException(TApplicationException.UNKNOWN_METHOD, 'Unknown function %s' % (name))
      oprot.writeMessageBegin(name, TMessageType.EXCEPTION, seqid)
      x.write(oprot)
      oprot.writeMessageEnd()
      oprot.trans.flush()
      return
    else:
      self._processMap[name](self, seqid, iprot, oprot)
    return True

  def process_parse(self, seqid, iprot, oprot):
    args = parse_args()
    args.read(iprot)
    iprot.readMessageEnd()
    result = parse_result()
    result.success = self._handler.parse(args.billercode, args.productcode, args.billnumber, args.bit61)
    oprot.writeMessageBegin("parse", TMessageType.REPLY, seqid)
    result.write(oprot)
    oprot.writeMessageEnd()
    oprot.trans.flush()

  def process_parse_prepaid(self, seqid, iprot, oprot):
    args = parse_prepaid_args()
    args.read(iprot)
    iprot.readMessageEnd()
    result = parse_prepaid_result()
    result.success = self._handler.parse_prepaid(args.billercode, args.productcode, args.billnumber, args.bit61, args.bit48)
    oprot.writeMessageBegin("parse_prepaid", TMessageType.REPLY, seqid)
    result.write(oprot)
    oprot.writeMessageEnd()
    oprot.trans.flush()


# HELPER FUNCTIONS AND STRUCTURES

class parse_args:
  """
  Attributes:
   - billercode
   - productcode
   - billnumber
   - bit61
  """

  thrift_spec = (
    None, # 0
    (1, TType.STRING, 'billercode', None, None, ), # 1
    (2, TType.STRING, 'productcode', None, None, ), # 2
    (3, TType.STRING, 'billnumber', None, None, ), # 3
    (4, TType.STRING, 'bit61', None, None, ), # 4
  )

  def __init__(self, billercode=None, productcode=None, billnumber=None, bit61=None,):
    self.billercode = billercode
    self.productcode = productcode
    self.billnumber = billnumber
    self.bit61 = bit61

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRING:
          self.billercode = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRING:
          self.productcode = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.STRING:
          self.billnumber = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.STRING:
          self.bit61 = iprot.readString();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('parse_args')
    if self.billercode is not None:
      oprot.writeFieldBegin('billercode', TType.STRING, 1)
      oprot.writeString(self.billercode)
      oprot.writeFieldEnd()
    if self.productcode is not None:
      oprot.writeFieldBegin('productcode', TType.STRING, 2)
      oprot.writeString(self.productcode)
      oprot.writeFieldEnd()
    if self.billnumber is not None:
      oprot.writeFieldBegin('billnumber', TType.STRING, 3)
      oprot.writeString(self.billnumber)
      oprot.writeFieldEnd()
    if self.bit61 is not None:
      oprot.writeFieldBegin('bit61', TType.STRING, 4)
      oprot.writeString(self.bit61)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class parse_result:
  """
  Attributes:
   - success
  """

  thrift_spec = (
    (0, TType.STRING, 'success', None, None, ), # 0
  )

  def __init__(self, success=None,):
    self.success = success

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 0:
        if ftype == TType.STRING:
          self.success = iprot.readString();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('parse_result')
    if self.success is not None:
      oprot.writeFieldBegin('success', TType.STRING, 0)
      oprot.writeString(self.success)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class parse_prepaid_args:
  """
  Attributes:
   - billercode
   - productcode
   - billnumber
   - bit61
   - bit48
  """

  thrift_spec = (
    None, # 0
    (1, TType.STRING, 'billercode', None, None, ), # 1
    (2, TType.STRING, 'productcode', None, None, ), # 2
    (3, TType.STRING, 'billnumber', None, None, ), # 3
    (4, TType.STRING, 'bit61', None, None, ), # 4
    (5, TType.STRING, 'bit48', None, None, ), # 5
  )

  def __init__(self, billercode=None, productcode=None, billnumber=None, bit61=None, bit48=None,):
    self.billercode = billercode
    self.productcode = productcode
    self.billnumber = billnumber
    self.bit61 = bit61
    self.bit48 = bit48

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRING:
          self.billercode = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRING:
          self.productcode = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.STRING:
          self.billnumber = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.STRING:
          self.bit61 = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 5:
        if ftype == TType.STRING:
          self.bit48 = iprot.readString();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('parse_prepaid_args')
    if self.billercode is not None:
      oprot.writeFieldBegin('billercode', TType.STRING, 1)
      oprot.writeString(self.billercode)
      oprot.writeFieldEnd()
    if self.productcode is not None:
      oprot.writeFieldBegin('productcode', TType.STRING, 2)
      oprot.writeString(self.productcode)
      oprot.writeFieldEnd()
    if self.billnumber is not None:
      oprot.writeFieldBegin('billnumber', TType.STRING, 3)
      oprot.writeString(self.billnumber)
      oprot.writeFieldEnd()
    if self.bit61 is not None:
      oprot.writeFieldBegin('bit61', TType.STRING, 4)
      oprot.writeString(self.bit61)
      oprot.writeFieldEnd()
    if self.bit48 is not None:
      oprot.writeFieldBegin('bit48', TType.STRING, 5)
      oprot.writeString(self.bit48)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class parse_prepaid_result:
  """
  Attributes:
   - success
  """

  thrift_spec = (
    (0, TType.STRING, 'success', None, None, ), # 0
  )

  def __init__(self, success=None,):
    self.success = success

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 0:
        if ftype == TType.STRING:
          self.success = iprot.readString();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('parse_prepaid_result')
    if self.success is not None:
      oprot.writeFieldBegin('success', TType.STRING, 0)
      oprot.writeString(self.success)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)
